In [1]:
import pandas as pd

In [2]:
filename = "data/FrogID4_gbif_database.csv"

# load the relevant columns only
# (others are either empty, contail all the same information or contain irrelevant information)
columns_to_load = [ 
      'gbifID', 'family', 'genus', 'species', 'stateProvince',
      'decimalLatitude', 'decimalLongitude', 'coordinateUncertaintyInMeters',
      'eventDate', 'day', 'month', 'year',
      'taxonKey', 'recordedBy' 
]

In [3]:
frogID_database = pd.read_csv(filename, usecols=columns_to_load, sep='\t', on_bad_lines='skip')
frogID_database

,gbifID,family,genus,species,stateProvince,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,eventDate,day,month,year,taxonKey,recordedBy
0,4138777961,Limnodynastidae,Limnodynastes,Limnodynastes peronii,New South Wales,-33.692792,150.364653,65.00,2020-11-20,20,11,2020,2429583,39341
1,3463473663,Myobatrachidae,Crinia,Crinia signifera,Queensland,-28.866000,151.965000,12.00,2021-01-11,11,1,2021,2424585,37463
2,4138921957,Limnodynastidae,Limnodynastes,Limnodynastes dumerilii,Victoria,-38.196269,145.230792,8.00,2019-09-22,22,9,2019,2429581,17362
3,4138775975,Pelodryadidae,Litoria,Litoria inermis,Queensland,-16.967100,145.453000,3.00,2019-01-09,9,1,2019,2427701,7876
4,4138775978,Pelodryadidae,Litoria,Litoria verreauxii,New South Wales,-35.133972,150.529508,165.00,2020-02-21,21,2,2020,2427755,21649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484222,3463473661,Limnodynastidae,Limnodynastes,Limnodynastes dorsalis,Western Australia,-32.214523,115.833349,10.00,2018-08-18,18,8,2018,2429585,14203
484223,4138777103,Pelodryadidae,Litoria,Litoria rubella,Queensland,-19.160400,146.563000,255.27,2018-02-21,21,2,2018,2427779,4199
484224,3463473662,Limnodynastidae,Limnodynastes,Limnodynastes peronii,Victoria,-37.832200,147.608000,41.37,2017-12-14,14,12,2017,2429583,230
484225,3463614590,Myobatrachidae,Crinia,Crinia georgiana,Western Australia,-31.936400,115.887000,4.12,2021-08-29,29,8,2021,2424597,12664
484226,3463614591,Microhylidae,Austrochaperina,Austrochaperina robusta,Queensland,-17.440625,145.457511,10.00,2019-01-25,25,1,2019,2421896,5208

In [4]:
recordedBy_counts = frogID_database.groupby('recordedBy').size().reset_index(name='counts')
recordedBy_counts = recordedBy_counts.sort_values(by='counts', ascending=False)
recordedBy_counts

       recordedBy  counts
6018        12664   15875
12700       27386   13588
1695         3687    6340
3556         7261    5668
9154        19452    4931
...           ...     ...
5020        10252       1
18962       41823       1
12963       28100       1
18960       41818       1
7818        16762       1

[23301 rows x 2 columns]