In [5]:
import pandas as pd

In [6]:
columns_to_load_territories_states = ['Postal', 'Population (Sept 2023)[17]', 'Area (km2)[18]']
url = "https://en.wikipedia.org/wiki/States_and_territories_of_Australia"

States_and_territories_of_Australia = pd.read_html(url, header=0)

## ---------------------------------------------------------
## wahrscheinlich sollte ich hier "https://en.wikipedia.org/wiki/States_and_territories_of_Australia"
## einfach die tabelle nehmen die bei statistics ist

In [7]:
# getting data on australias states and cleaning it
states_of_australia = States_and_territories_of_Australia[2]
states_of_australia_filtered = states_of_australia[['State'] + columns_to_load_territories_states]
states_of_australia_filtered = states_of_australia_filtered.rename(columns={'State': 'State or Territory'})

# getting data on australias terretories and cleaning it + erasing 'Jervis Bay Territory'
territories_of_australia = States_and_territories_of_Australia[3]
territories_of_australia = territories_of_australia[territories_of_australia['Territory'] != 'Jervis Bay Territory']
territories_of_australia_filtered = territories_of_australia[['Territory'] + columns_to_load_territories_states]
territories_of_australia_filtered = territories_of_australia_filtered.rename(columns={'Territory': 'State or Territory'})

In [8]:
states_and_territories = pd.merge(states_of_australia_filtered, territories_of_australia_filtered, how='outer').set_index('Postal')
states_and_territories = states_and_territories.rename(columns={'Population (Sept 2023)[10]': 'Population (Sept 2023)'})
states_and_territories = states_and_territories.rename(columns={'Area (km2)[11]': 'Area (km2)'})

states_and_territories

,State or Territory,Population (Sept 2023)[17],Area (km2)[18]
Postal,,,
NSW,New South Wales,8394714,800150
VIC,Victoria,6865358,227416
QLD,Queensland,5495524,1729742
WA,Western Australia,2905922,2527013
SA,South Australia,1860054,984321
TAS,Tasmania,573328,64519
ACT,Australian Capital Territory,469194,2358
NT,Northern Territory,252469,1347791

In [26]:
states_and_territories_of_australia = States_and_territories_of_Australia[6].drop(0).reset_index()
states_and_territories_of_australia = states_and_territories_of_australia[['Abbreviation', 'State / territory']]
states_and_territories_of_australia = states_and_territories_of_australia.rename(columns={'Abbreviation': 'stateProvinceShort', 'State / territory': 'stateProvince'})
states_and_territories_of_australia

  stateProvinceShort                 stateProvince
0                NSW               New South Wales
1                VIC                      Victoria
2                QLD                    Queensland
3                 WA             Western Australia
4                 SA               South Australia
5                TAS                      Tasmania
6                ACT  Australian Capital Territory
7                 NT            Northern Territory